### PR TITLE
Merging from Develop -- I'm not sure what the conflicts are.

### PR DESCRIPTION
**Pull request by edjuaro**

### CODE REVIEW

**Comment by edjuaro** [comment]
Ah! Yes, I modified the readme on master by accident. It's okay to override!

**Comment by bahill** [comment]
Should you also rename the docker image? https://github.com/genepattern/VoomNormalize/pull/2/commits/372e0fc3886ab74ef1da45d0d43d9c995c0c53c6

**Comment by edjuaro** [comment]
Copy paste from slack: Last time we renamed a module we left the docker image the same — conceptually I can see how the name of the image could be different (since we even have multiple modules use the same container) but if we agree to also change container names, I can take a look at that tomorrow.

**Comment by edjuaro** [comment]
@bahill I think we never closed this pull request, but now it's read with the revisions we made for version 1.0. (GPUnits passed)

**Comment by bahill** [comment]
@edjuaro it doesn't look like the documentation and license changes made it into v 1.0 - based on these commit statements and what I'm seeing on gpbeta.  Am I missing something?

**Comment by edjuaro** [comment]
Ah! You are right @bahill , I released version 1.0 on Jenkins before making this changes. Should I release version 1.1 on Jenkins to include the updated documentation?

**Comment by bahill** [comment]
(see eye roll for version weirdness) But given where we  are now - yes, just call it v1.1 - if you REALLY want to you can re-release as 1.0, but it's about 12 more steps of tedious work - not hard, but tedious and error-prone)
Let me know if you want to re-release and I can show you after the scrum (and doc it)

**Comment by edjuaro** [comment]
I'll just release 1.1 -- I'm not sure if I want to deal with tags and whatnot, it's been more work than it's worth it in the past.

**Comment by bahill** [comment]
@edjuaro 100%

**Comment by bahill** [comment]
I'll review again after a quick check of 1.1 on beta - just let me know when it's up.

**Comment by edjuaro** [comment]
@bahill I think the documentation displays correctly now.

**Pull request merged**
